# 1. Python

※Pythonある程度書けます！という方はこの章を飛ばして下さい

## Pythonとは？

Pythonは，構文がシンプルな軽量スクリプト型プログラミング言語です．  
ここでは，本ハンズオンを行う上で必要そうな内容をかいつまんで紹介します．

・・・の前に，この実行環境について簡単な操作方法を説明しましょう．  
この実行環境では，左側に `In []` が表示された以下の様なセル上でPythonのコードを実行することができます．  
試してみましょう．以下のセルにカーソルを合わせて，shift+enter を押して下さい．

In [1]:
print('Hello World!')

Hello World!


プログラムが正しく実行されたら，`Hello World!` という実行結果が表示されているはずです．

### インデントをブロックとして利用

Pythonの大きな特徴の一つに，ブロックを表現する際 `{}` や `begin ... end` を使わずインデントを使うという点が挙げられます．例を見てみましょう．  
以下のセル上で shift+enter を押して書かれているプログラムを実行してみて下さい．

In [2]:
# Hello World という関数を定義
def print_helloworld():
    print('Hello World!')

# 定義した関数を呼び出し
print_helloworld()

Hello World!


プログラムが正しく実行出来れば，`Hello World!` が表示されます．  
ここで，`print('Hello World')` の前のスペースを全て消してプログラムを実行するとどうなるでしょうか？

...

`IndentationError` が発生するかと思います．これはプログラムがインデントをブロックとして解釈しているためです．  
不用意にインデントを削除するとプログラムが動作しなくなることがあるため，注意して下さい．

### 行列の処理

機械学習をする上でほとんどのデータは行列形式で与えられますので，行列操作について学んでおきましょう．  
Pythonにおける行列演算には，`numpy` というライブラリを利用します．

まずは以下を実行してみましょう．

In [3]:
import numpy as np

a = np.array([1, 2, 3])  # 1, 2, 3の要素が入った1次行列を作る
a

array([1, 2, 3])

In [4]:
b = np.array([[1.5, 0], [2.0, 3.0]])  # 2次行列を作る
b

array([[ 1.5,  0. ],
       [ 2. ,  3. ]])

インデックスを利用して行列の要素へアクセス出来ます（他のプログラミング言語と同じです）    
以下を実行してみましょう．

In [5]:
a[0]  # 0番目の要素にアクセス

1

bの行列の3.0の要素にアクセスするには以下のように書きます．実行してみましょう．

In [6]:
b[1, 1]  # b[1][1] とも書ける．同義

3.0

bの行列の2.0の要素にアクセスしてみましょう．

In [7]:
# bの行列の2.0の要素にアクセス
b[1, 0]

2.0

行列の大きさを知るためには，`.shape` を使います．  
以下を実行してみましょう．

In [8]:
a.shape

(3,)

上記の結果は (3, 1) と同義です．大きさが1の場合は省略して書かれます．  
bの行列の大きさを確認してみて下さい．

In [9]:
# bの行列の大きさを確認
b.shape

(2, 2)

今回の例は非常に小さな行列ですが，機械学習ではえてして大規模なデータを扱うことが多いため，行列の中身の一部だけを確認する方法も勉強しておきましょう．  
行列の一部を確認するにはスライス操作が便利です．

スライス操作：  
a [ start : end ] --> [ start, ..., end-1 ]  ( start, end はどちらも数字 )

start / end の数字を変更することで，巨大な行列から任意の大きさの行列を一部取り出して確認することができます．  
以下を実行してみましょう．

In [10]:
a[0:2]  # a[:2] とも書けます

array([1, 2])

行列の0番目から，2-1=1番目までの要素を取り出して確認することができました．  
`:` のみを利用するとその行列中の全ての要素を返してきます．  
以下を実行してみましょう．

In [11]:
a[:]

array([1, 2, 3])

ここまでのテクニックを組み合わせてみましょう（ややこしくなって参りました）  
各行の0番目の要素にアクセスするには以下のように書きます．

In [12]:
b[:, 0]

array([ 1.5,  2. ])

`array([0., 3.0])` の結果を得るためには，bの行列に対してどのような操作をすればよいでしょうか？

In [13]:
# bの行列へどのようにアクセスすれば `array([0., 3.0])` の結果が得られる？
b[:, 1]

array([ 0.,  3.])

最後におさらいです．以下のような `c` という行列を定義します．  
この行列の

- 行列のサイズはどうなっていますか？
- 各行の最初の10列を確認してみて下さい

In [14]:
c = np.array([np.linspace(10, 100, 50), np.linspace(0, 1, 50), np.linspace(10, 20, 50)])

In [15]:
# 行列のサイズは？
c.shape

(3, 50)

In [16]:
# 各行の最初の10列を表示
c[:, :10]

array([[  1.00000000e+01,   1.18367347e+01,   1.36734694e+01,
          1.55102041e+01,   1.73469388e+01,   1.91836735e+01,
          2.10204082e+01,   2.28571429e+01,   2.46938776e+01,
          2.65306122e+01],
       [  0.00000000e+00,   2.04081633e-02,   4.08163265e-02,
          6.12244898e-02,   8.16326531e-02,   1.02040816e-01,
          1.22448980e-01,   1.42857143e-01,   1.63265306e-01,
          1.83673469e-01],
       [  1.00000000e+01,   1.02040816e+01,   1.04081633e+01,
          1.06122449e+01,   1.08163265e+01,   1.10204082e+01,
          1.12244898e+01,   1.14285714e+01,   1.16326531e+01,
          1.18367347e+01]])